In [3]:
import numpy as np
import plotly.graph_objects as go

In [4]:
#Dataset

x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

In [5]:
x.shape, y.shape

((4, 2), (4, 1))

In [6]:
# 4x2 * 2x2 + 1x2
# 0 0                   
# 0 1   r r   +  b b     
# 1 0   r r   +       
# 1 1            

In [7]:
rng = np.random.default_rng(42)

In [8]:
#Hidden layer (2 neurons)
n_hidden = 2 # 4 for experimentation
fan_in = 2

W1 = rng.normal(0, 1, (fan_in, n_hidden)) / fan_in**0.5 
b1 = np.zeros((1, n_hidden))

#Output layer (1 neuron)
n_output = 1

W2 = rng.normal(0, 1, (fan_in, n_output)) 
b2 = np.zeros((1, n_output))

In [9]:
x.shape, W1.shape, b1.shape

((4, 2), (2, 2), (1, 2))

In [10]:
# 4x2 * 2x1 + 1x2
# z11 z12
# z21 z22   r  +  b
# z31 z32   r  +  
# z41 z42

In [11]:
# Forward flow of the Network
Z1 = x @ W1 + b1
A1 = np.tanh(Z1)

output = A1 @ W2 + b2
A2 = 1/(1 + np.exp(-output))

#Loss function (MSE loss)

loss = ((y- A2)**2).mean()
loss #Current loss


0.2963268025779074

In [12]:
output.shape

(4, 1)

In [14]:
#backpropagation & Training the model

max_steps = 10000
lossi = []

for i in range(max_steps):

    #forward pass
    Z1 = x @ W1 + b1
    A1 = np.tanh(Z1)
    Z2 = A1 @ W2 + b2
    A2 = 1/(1 + np.exp(-Z2))
    loss = ((y-A2)**2).mean()

    #backward pass
    m = x.shape[0]
    dA2 = (2/m) * (A2 - y)
    dZ2 = A2 * (1 - A2) * dA2
    dA1 = dZ2 @ W2.T
    dW2 = A1.T @ dZ2
    db2 = np.sum(dZ2, axis=0, keepdims=True)
    dZ1 = (1 - A1**2) * dA1
    dW1 = x.T @ dZ1
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    #update
    if i<5000:
        lr = 0.1
    elif (i>5000 and i<7500):
        lr = 0.01
    else: 
        lr = 0.001
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2

    #track stats
    lossi.append(loss)
    if i%1000 == 0:
        print(f"Step: {i}/{max_steps} | Loss: {loss.item():.4f}")


Step: 0/10000 | Loss: 0.2963
Step: 1000/10000 | Loss: 0.0416
Step: 2000/10000 | Loss: 0.0086
Step: 3000/10000 | Loss: 0.0045
Step: 4000/10000 | Loss: 0.0030
Step: 5000/10000 | Loss: 0.0022
Step: 6000/10000 | Loss: 0.0022
Step: 7000/10000 | Loss: 0.0021
Step: 8000/10000 | Loss: 0.0021
Step: 9000/10000 | Loss: 0.0021


In [15]:
W2.shape, A1.shape, dZ2.shape

((2, 1), (4, 2), (4, 1))

In [16]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.arange(max_steps), y=lossi, mode='lines', name='Run-1'))
fig.update_layout(
    hovermode="x unified",
    xaxis_title="Steps",
    yaxis_title="Loss",
    template="plotly_dark"
)
fig.show()

In [17]:
#Model output vs ground truth
print(A2)
print(y)

[[0.04085562]
 [0.94736438]
 [0.94856999]
 [0.03553828]]
[[0]
 [1]
 [1]
 [0]]


In [18]:
#Rounding the outputs for clear picture
print(A2.round())

[[0.]
 [1.]
 [1.]
 [0.]]
